# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 962120c72ae06b477fd95e8ab82a9f129f6979ec8b3dc1138fc937c56826407284f2ca9e8d901b2780744aa3ad66e3144d34115b37176bd808bebd98faf19b24

test:
  secret_key_base: 5718b51a8c2d85253adbf69ffd24917663cd9d76fb1b783ce62d6fdce75739a0086a2524790028eafb5e5c1bcd55f16a64bfd92da4595bf4e8d5e87380f8e79a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
